### ISSUE TITLE
gdbdump/gdb.rb:12: syntax error, unexpected ',' (SyntaxError)

### ISSUE THREAD

**Issue by clintmod** [sonots/gdbdump-ruby#3]
Hi I just installed your gem and tried to use it but got the error mentioned in the subject.

Thoughts?

```
[deploy@stg-app02 current]$ gdbdump 7383
/usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/lib/gdbdump.rb:7:in `require_relative': /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/lib/gdbdump/gdb.rb:12: syntax error, unexpected ',' (SyntaxError)
...ialize(ruby: nil, pid_or_core:, debug: false, gdbinit: nil, ...
...                               ^
/usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/lib/gdbdump/gdb.rb:12: Can't assign to false
...il, pid_or_core:, debug: false, gdbinit: nil, gdb: nil)
...                               ^
/usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/lib/gdbdump/gdb.rb:12: Can't assign to nil
...e:, debug: false, gdbinit: nil, gdb: nil)
...                               ^
/usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/lib/gdbdump/gdb.rb:127: syntax error, unexpected keyword_end, expecting end-of-input
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/lib/gdbdump.rb:7:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/lib/gdbdump/cli.rb:2:in `require_relative'
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/lib/gdbdump/cli.rb:2:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/exe/gdbdump:3:in `require_relative'
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/gems/gdbdump-0.9.4/exe/gdbdump:3:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/bin/gdbdump:23:in `load'
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/bin/gdbdump:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.0.0-p648@oceans/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by sonots** [comment]
ruby 2.0 is not supported

**Comment by sonots** [comment]
ruby 2.0 is EOL already (actually, ruby 2.1 is also already EOL)

**Comment by clintmod** [comment]
roger that… closing the issue
